name: McMasterful Books Backend CI

on: 
    push: 
    pull_request:

jobs:
    format_and_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
              working-directory: services/listings
            - run: npm run lint
              working-directory: services/listings
    
    check_types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
              working-directory: services/listings
            - run: npm run check-types
              working-directory: services/listings

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
              working-directory: services/listings
            - run: npm run test:ci
              working-directory: services/listings

    generate-client:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
              working-directory: services/listings
            - run: ./generate-openapi.sh
              working-directory: services/listings
            - uses: actions/upload-artifact@v4
              with:
                name: client-sdk
                path: services/listings/client/